"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { unzipSync, strFromU8 } from "fflate";
import * as maplibregl from "maplibre-gl";
import { AlertTriangle, CheckCircle2, Crosshair, Database, FileUp, LandPlot, Layers3, Loader2, MapPin, MousePointer2, RotateCcw, Ruler, Satellite, ShieldAlert, Waves } from "lucide-react";
import { toast } from "sonner";

type Point=[number,number];
type Source={name:string;provider:string;url:string;queriedAt:string;status:"consultado"|"indisponível";detail:string};
type Analysis={generatedAt:string;location?:{displayName?:string;municipality?:string;state?:string;ibgeCode?:string};terrain?:{min:number;max:number;mean:number;amplitude:number;samples:number};context?:{nearestRoad?:{name:string;distanceM:number;kind:string};nearestWater?:{name:string;distanceM:number};roads:number;waterways:number;health:number;education:number;power:number;urbanLanduse:number};market?:{provider:string;period?:string;pageUrl:string;population?:string;formalJobs?:string;gdp?:string;gdpPerCapita?:string;admissions?:string;dismissals?:string;jobBalance?:string;newCompanies?:string;note?:string};sources:Source[];limitations:string[]};
const STREET_STYLE="https://tiles.openfreemap.org/styles/liberty";
const SATELLITE_STYLE:any={version:8,sources:{satellite:{type:"raster",tiles:["https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"],tileSize:256,attribution:"Tiles © Esri — Esri, Maxar, Earthstar Geographics and contributors"}},layers:[{id:"satellite",type:"raster",source:"satellite"}]};
const rad=(v:number)=>v*Math.PI/180;
function distance(a:Point,b:Point){const R=6371008.8,dLat=rad(b[1]-a[1]),dLon=rad(b[0]-a[0]),q=Math.sin(dLat/2)**2+Math.cos(rad(a[1]))*Math.cos(rad(b[1]))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function polygonArea(p:Point[]){if(p.length<3)return 0;const R=6378137,lat0=rad(p.reduce((s,x)=>s+x[1],0)/p.length),xy=p.map(x=>[R*rad(x[0])*Math.cos(lat0),R*rad(x[1])] as Point);let sum=0;for(let i=0;i<xy.length;i++){const j=(i+1)%xy.length;sum+=xy[i][0]*xy[j][1]-xy[j][0]*xy[i][1]}return Math.abs(sum)/2}
const perimeter=(p:Point[])=>p.length<2?0:p.reduce((s,x,i)=>s+distance(x,p[(i+1)%p.length]),0);
const centroid=(p:Point[]):Point=>[p.reduce((s,x)=>s+x[0],0)/p.length,p.reduce((s,x)=>s+x[1],0)/p.length];
function parseKml(xml:string){const doc=new DOMParser().parseFromString(xml,"application/xml");if(doc.querySelector("parsererror"))throw new Error("KML inválido ou corrompido.");const rings=[...doc.querySelectorAll("Polygon outerBoundaryIs LinearRing coordinates, Polygon coordinates")];if(!rings.length)throw new Error("Nenhuma poligonal foi encontrada no arquivo.");return rings.map(r=>(r.textContent||"").trim().split(/\s+/).map(v=>v.split(",").slice(0,2).map(Number) as Point).filter(x=>Number.isFinite(x[0])&&Number.isFinite(x[1]))).sort((a,b)=>b.length-a.length)[0]}
export default function TerritorialIntelligence(){
 const [points,setPoints]=useState<Point[]>([]),[drawing,setDrawing]=useState(false),[fileName,setFileName]=useState(""),[analysis,setAnalysis]=useState<Analysis|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[base,setBase]=useState<"streets"|"satellite">("streets"),[mapReady,setMapReady]=useState(false);
 const input=useRef<HTMLInputElement>(null),container=useRef<HTMLDivElement>(null),mapRef=useRef<any>(null),drawingRef=useRef(false),pointsRef=useRef<Point[]>([]);
 const area=useMemo(()=>polygonArea(points),[points]),length=useMemo(()=>perimeter(points),[points]),center=points.length?centroid(points):null;
 useEffect(()=>{drawingRef.current=drawing},[drawing]);useEffect(()=>{pointsRef.current=points},[points]);
 function data(p=pointsRef.current){return{type:"FeatureCollection",features:p.length>=3?[{type:"Feature",properties:{},geometry:{type:"Polygon",coordinates:[[...p,p[0]]]}}]:[]}}
 function sync(fit=false){const map=mapRef.current;if(!map||!map.isStyleLoaded())return;const src=map.getSource("area");if(src)src.setData(data());else{map.addSource("area",{type:"geojson",data:data()});map.addLayer({id:"area-fill",type:"fill",source:"area",paint:{"fill-color":"#f36a21","fill-opacity":.25}});map.addLayer({id:"area-line",type:"line",source:"area",paint:{"line-color":"#ff6b20","line-width":3}})}if(fit&&pointsRef.current.length){const xs=pointsRef.current.map(x=>x[0]),ys=pointsRef.current.map(x=>x[1]);map.fitBounds([[Math.min(...xs),Math.min(...ys)],[Math.max(...xs),Math.max(...ys)]],{padding:55,maxZoom:17,duration:900})}}
 useEffect(()=>{if(!container.current)return;const map=new maplibregl.Map({container:container.current,style:STREET_STYLE,center:[-47.5,-18.73],zoom:7,attributionControl:{}});mapRef.current=map;map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),"top-right");map.addControl(new maplibregl.ScaleControl({unit:"metric"}),"bottom-left");map.addControl(new maplibregl.GeolocateControl({positionOptions:{enableHighAccuracy:true},trackUserLocation:true}),"top-right");map.on("load",()=>{setMapReady(true);sync()});map.on("error",(event:any)=>{if(!event?.error?.message?.includes("tile"))setError("A camada cartográfica apresentou uma falha de carregamento.")});map.on("click",(e:any)=>{if(drawingRef.current){setPoints(p=>[...p,[e.lngLat.lng,e.lngLat.lat]]);setAnalysis(null)}});return()=>{map.remove();mapRef.current=null}},[]);
 useEffect(()=>{sync()},[points,mapReady]);
 function basemap(next:"streets"|"satellite"){setBase(next);const map=mapRef.current;if(!map)return;map.setStyle(next==="streets"?STREET_STYLE:SATELLITE_STYLE);map.once("styledata",()=>sync())}
 async function openFile(file?:File){if(!file)return;setError("");try{let xml="";if(file.name.toLowerCase().endsWith(".kmz")){const zip=unzipSync(new Uint8Array(await file.arrayBuffer())),key=Object.keys(zip).find(k=>k.toLowerCase().endsWith(".kml"));if(!key)throw new Error("O KMZ não contém um arquivo KML.");xml=strFromU8(zip[key])}else xml=await file.text();const parsed=parseKml(xml);if(parsed.length<3)throw new Error("A poligonal precisa ter ao menos três vértices.");setPoints(parsed);pointsRef.current=parsed;setFileName(file.name);setAnalysis(null);setTimeout(()=>sync(true),180);toast.success(`${parsed.length} vértices importados e enquadrados`)}catch(e){const msg=e instanceof Error?e.message:"Falha ao ler o arquivo";setError(msg);toast.error(msg)}}
 function clear(){setPoints([]);pointsRef.current=[];setAnalysis(null);setFileName("");setError("");sync()}
 async function run(){if(points.length<3)return toast.error("Importe ou desenhe uma poligonal válida.");setLoading(true);setError("");try{const res=await fetch("/api/territorial-analysis",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({coordinates:points})}),result=await res.json();if(!res.ok)throw new Error(result.error||"A análise não pôde ser concluída.");setAnalysis(result);toast.success("Análise concluída; falhas externas foram isoladas")}catch(e){setError(e instanceof Error?e.message:"Erro na análise")}finally{setLoading(false)}}
 const facts=[["Vias mapeadas",analysis?.context?.roads],["Cursos/espelhos d’água",analysis?.context?.waterways],["Saúde",analysis?.context?.health],["Educação",analysis?.context?.education],["Infraestrutura elétrica",analysis?.context?.power],["Polígonos de uso urbano",analysis?.context?.urbanLanduse]];
 const market=[["População",analysis?.market?.population],["Empregos formais",analysis?.market?.formalJobs],["PIB",analysis?.market?.gdp],["PIB per capita",analysis?.market?.gdpPerCapita],["Admissões",analysis?.market?.admissions],["Desligamentos",analysis?.market?.dismissals],["Saldo de empregos",analysis?.market?.jobBalance],["Novas empresas",analysis?.market?.newCompanies]].filter(x=>x[1]);
 return <div className="ti"><div className="ti-head"><div><p>ÉVORA INTELLIGENCE · MALHA</p><h1>Inteligência territorial</h1><span>Mapa geográfico interativo e análise rastreável por fonte.</span></div><div className="ti-real"><CheckCircle2/> DADOS REAIS</div></div>
  <div className="ti-toolbar"><input ref={input} hidden type="file" accept=".kml,.kmz" onChange={e=>openFile(e.target.files?.[0])}/><button className="accent" onClick={()=>input.current?.click()}><FileUp/> Importar KML / KMZ</button><button className={drawing?"active":""} onClick={()=>setDrawing(v=>!v)}><MousePointer2/> {drawing?"Concluir desenho":"Desenhar poligonal"}</button><button onClick={clear}><RotateCcw/> Limpar</button><div className="ti-file">{fileName||(drawing?"Toque no mapa para marcar vértices":"Mapa WGS84 · EPSG:4326")}</div></div>
  {error&&<div className="ti-error"><AlertTriangle/>{error}</div>}
  <div className="ti-grid"><section className="ti-map"><div className="ti-layerbar"><button className={base==="streets"?"active":""} onClick={()=>basemap("streets")}><Layers3/> Ruas</button><button className={base==="satellite"?"active":""} onClick={()=>basemap("satellite")}><Satellite/> Satélite</button><button disabled={!points.length} onClick={()=>sync(true)}><Crosshair/> Enquadrar área</button></div><div ref={container} className={drawing?"ti-real-map drawing":"ti-real-map"}/>{!mapReady&&<div className="ti-map-loading"><Loader2 className="spin"/> Carregando cartografia…</div>}<div className="ti-map-foot"><span>Arraste, aproxime e gire</span><span>{analysis?.location?.municipality?`${analysis.location.municipality} · ${analysis.location.state||"Brasil"}`:"Importe a área para identificar o município"}</span><span>{center?`${center[1].toFixed(5)}, ${center[0].toFixed(5)}`:"WGS84"}</span></div></section>
   <aside className="ti-side"><div className="ti-measure"><Ruler/><span>Área geodésica aproximada</span><b>{points.length?area>=1e6?`${(area/1e6).toLocaleString("pt-BR",{maximumFractionDigits:2})} km²`:`${(area/10000).toLocaleString("pt-BR",{maximumFractionDigits:2})} ha`:"—"}</b><small>Cálculo determinístico WGS84</small></div><div className="ti-measure"><LandPlot/><span>Perímetro</span><b>{points.length?`${(length/1000).toLocaleString("pt-BR",{maximumFractionDigits:2})} km`:"—"}</b><small>{points.length} vértices válidos</small></div><div className="ti-measure"><MapPin/><span>Centroide / localização</span><b>{analysis?.location?.municipality||(center?`${center[1].toFixed(5)}, ${center[0].toFixed(5)}`:"—")}</b><small>{analysis?.location?.displayName||fileName||"Nenhuma área carregada"}</small></div><button className="ti-run" disabled={loading||points.length<3} onClick={run}>{loading?<Loader2 className="spin"/>:<Satellite/>}{loading?"Consultando fontes...":"Executar análise profunda"}</button></aside></div>
  {analysis&&<div className="ti-results"><div className="ti-results-head"><div><p>RELATÓRIO TERRITORIAL</p><h2>{analysis.location?.municipality||"Localização analisada"}{analysis.location?.state?` · ${analysis.location.state}`:""}</h2><span>{analysis.location?.displayName||"Centroide identificado pelas coordenadas"}</span></div><span>Data-base: {new Date(analysis.generatedAt).toLocaleString("pt-BR")}</span></div>
   <div className="ti-kpis"><article><Database/><span>Código IBGE</span><b>{analysis.location?.ibgeCode||"Não identificado"}</b></article><article><Satellite/><span>Elevação observada</span><b>{analysis.terrain?`${analysis.terrain.min}–${analysis.terrain.max} m`:"Fonte indisponível"}</b><small>{analysis.terrain?`${analysis.terrain.samples} amostras · amplitude ${analysis.terrain.amplitude} m`:"Sem estimativa substituta"}</small></article><article><Crosshair/><span>Acesso viário mais próximo</span><b>{analysis.context?.nearestRoad?.name||"Não identificado"}</b><small>{analysis.context?.nearestRoad?`${analysis.context.nearestRoad.distanceM.toLocaleString("pt-BR")} m · ${analysis.context.nearestRoad.kind}`:"Consulta sem retorno"}</small></article><article><Waves/><span>Feição hídrica mais próxima</span><b>{analysis.context?.nearestWater?.name||"Não identificada"}</b><small>{analysis.context?.nearestWater?`${analysis.context.nearestWater.distanceM.toLocaleString("pt-BR")} m do centroide`:"Não inferida"}</small></article></div>
   {analysis.market&&<section className="ti-market"><div><p>CARAVELA · PERFIL MUNICIPAL</p><h3>{analysis.location?.municipality}</h3><span>{analysis.market.period||"Última informação pública identificável"}</span></div><div className="ti-market-values">{market.map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><a href={analysis.market.pageUrl} target="_blank" rel="noreferrer">Abrir fonte original na Caravela ↗</a>{analysis.market.note&&<small>{analysis.market.note}</small>}</section>}
   <div className="ti-analysis-grid"><section><h3>Contexto observado no OpenStreetMap</h3><div className="ti-facts">{facts.map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]??"—"}</b></div>)}</div><p className="ti-note">As contagens refletem o cadastro aberto do OSM no recorte. Ausência de cadastro não prova inexistência física.</p></section><section><h3>Conclusão responsável</h3><div className="ti-conclusion"><ShieldAlert/><div><b>Sem score automático sem bases oficiais suficientes</b><p>Zoneamento, matrícula, infraestrutura, restrições ambientais e mercado precisam ser confirmados antes de recomendar aquisição.</p></div></div><h3>Limitações registradas</h3>{analysis.limitations.map(x=><div className="ti-limit" key={x}><AlertTriangle/>{x}</div>)}</section></div>
   <section className="ti-sources"><h3>Fontes e status desta execução</h3>{analysis.sources.map(s=><a key={s.name} href={s.url} target="_blank" rel="noreferrer"><span className={s.status}/><div><b>{s.name}</b><small>{s.provider} · {s.detail}</small></div><em>{s.status} · {new Date(s.queriedAt).toLocaleString("pt-BR")}</em></a>)}</section>
   <section className="ti-official"><h3>Camadas oficiais para due diligence completa</h3>{[{n:"IDE-Sisema/MG",d:"Restrições ambientais e recursos hídricos estaduais.",u:"https://visualizador.idesisema.meioambiente.mg.gov.br/"},{n:"IBGE",d:"Limites, setores censitários e estatísticas oficiais.",u:"https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais.html"},{n:"ANA / BHO6",d:"Hidrografia e áreas de drenagem.",u:"https://www.gov.br/ana/pt-br/assuntos/monitoramento-e-eventos-criticos/monitoramento-hidrologico/portal-de-metadados-da-ana"},{n:"ICMBio",d:"Unidades de conservação federais.",u:"https://www.gov.br/icmbio/pt-br/dados-icmbio/dados_geoespaciais/mapa-tematico-e-dados-geoestatisticos-das-unidades-de-conservacao-federais"},{n:"FUNAI",d:"Terras indígenas e geoprocessamento.",u:"https://www.gov.br/funai/pt-br/atuacao/terras-indigenas/geoprocessamento-e-mapas"},{n:"INPE TerraBrasilis",d:"PRODES e DETER.",u:"https://www.gov.br/inpe/pt-br/assuntos/produtos/desmatamento"}].map(x=><a key={x.n} href={x.u} target="_blank" rel="noreferrer"><b>{x.n}</b><span>{x.d}</span></a>)}</section></div>}
 </div>
}
