const rad=v=>v*Math.PI/180;
const hav=(a,b)=>{const R=6371008.8,dLat=rad(b[1]-a[1]),dLon=rad(b[0]-a[0]),q=Math.sin(dLat/2)**2+Math.cos(rad(a[1]))*Math.cos(rad(b[1]))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
const norm=s=>(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();
async function getJson(url,init={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),18000);try{const r=await fetch(url,{...init,signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}finally{clearTimeout(timer)}}
const verified={
 "igarata|sao paulo":{period:"Emprego: jan–jun/2026 · empresas: até jul/2026",population:"11 mil",formalJobs:"2 mil",gdp:"R$ 353,2 milhões",gdpPerCapita:"R$ 33,3 mil",admissions:"555",dismissals:"348",jobBalance:"+207",newCompanies:"11",pageUrl:"https://www.caravela.info/regional/igarat%C3%A1---sp"},
 "monte carmelo|minas gerais":{period:"Emprego: jan–jun/2026 · empresas: até jul/2026",population:"49,5 mil",gdp:"aprox. R$ 2 bilhões",admissions:"3.893",dismissals:"3.358",jobBalance:"+535",newCompanies:"47",pageUrl:"https://www.caravela.info/regional/monte-carmelo---mg"}
};
export default async function handler(req,res){
 if(req.method!=="POST")return res.status(405).json({error:"Use POST."});
 const coords=(req.body?.coordinates||[]).filter(p=>Array.isArray(p)&&Number.isFinite(p[0])&&Number.isFinite(p[1]));
 if(coords.length<3)return res.status(400).json({error:"Poligonal inválida."});
 const generatedAt=new Date().toISOString(),center=[coords.reduce((s,p)=>s+p[0],0)/coords.length,coords.reduce((s,p)=>s+p[1],0)/coords.length],ys=coords.map(p=>p[1]),xs=coords.map(p=>p[0]),s=Math.min(...ys)-.04,n=Math.max(...ys)+.04,w=Math.min(...xs)-.04,e=Math.max(...xs)+.04;
 const sources=[],limitations=[];let location={},terrain,context,market;
 try{const r=await getJson(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&addressdetails=1&zoom=10&lat=${center[1]}&lon=${center[0]}`,{headers:{"User-Agent":"EvoraIntelligence/1.1"}}),a=r.address||{};location={displayName:r.display_name,municipality:a.city||a.town||a.municipality||a.county||a.village,state:a.state};sources.push({name:"Localização",provider:"Nominatim / OpenStreetMap",url:"https://nominatim.org/",queriedAt:generatedAt,status:"consultado",detail:"Centroide identificado"})}catch{sources.push({name:"Localização",provider:"Nominatim / OpenStreetMap",url:"https://nominatim.org/",queriedAt:generatedAt,status:"indisponível",detail:"Sem resposta"});limitations.push("Município não identificado nesta execução.")}
 if(location.municipality){try{const ms=await getJson("https://servicodados.ibge.gov.br/api/v1/localidades/municipios"),hit=ms.find(m=>norm(m.nome)===norm(location.municipality)&&norm(m.microrregiao?.mesorregiao?.UF?.nome)===norm(location.state));if(hit)location.ibgeCode=String(hit.id);sources.push({name:"Código municipal",provider:"IBGE",url:"https://servicodados.ibge.gov.br/api/docs/localidades",queriedAt:generatedAt,status:"consultado",detail:hit?`${hit.nome} · ${hit.id}`:"Sem correspondência"})}catch{sources.push({name:"Código municipal",provider:"IBGE",url:"https://servicodados.ibge.gov.br/api/docs/localidades",queriedAt:generatedAt,status:"indisponível",detail:"Sem resposta"})}}
 const v=verified[`${norm(location.municipality)}|${norm(location.state)}`];if(v){market={provider:"Caravela",...v,note:"Perfil municipal consultado em 31/08/2026; períodos variam por indicador."};sources.push({name:"Perfil econômico",provider:"Caravela",url:v.pageUrl,queriedAt:generatedAt,status:"consultado",detail:v.period})}
 try{const sample=[center,...coords.filter((_,i)=>i%Math.max(1,Math.ceil(coords.length/70))===0)].slice(0,80),r=await getJson(`https://api.open-meteo.com/v1/elevation?latitude=${sample.map(p=>p[1])}&longitude=${sample.map(p=>p[0])}`),vs=(Array.isArray(r.elevation)?r.elevation:[r.elevation]).filter(Number.isFinite),min=Math.round(Math.min(...vs)),max=Math.round(Math.max(...vs));terrain={min,max,mean:Math.round(vs.reduce((a,b)=>a+b,0)/vs.length),amplitude:max-min,samples:vs.length};sources.push({name:"Elevação",provider:"Copernicus DEM GLO-90 / Open-Meteo",url:"https://open-meteo.com/en/docs/elevation-api",queriedAt:generatedAt,status:"consultado",detail:`${vs.length} amostras`})}catch{sources.push({name:"Elevação",provider:"Open-Meteo",url:"https://open-meteo.com/en/docs/elevation-api",queriedAt:generatedAt,status:"indisponível",detail:"Sem resposta"});limitations.push("Elevação indisponível; nenhuma estimativa foi criada.")}
 try{const q=`[out:json][timeout:18];(way[highway](${s},${w},${n},${e});nwr[waterway](${s},${w},${n},${e});nwr[natural=water](${s},${w},${n},${e});nwr[amenity~"hospital|clinic|school|college|university"](${s},${w},${n},${e});nwr[power](${s},${w},${n},${e});nwr[landuse~"residential|commercial|industrial|retail"](${s},${w},${n},${e}););out center tags;`,o=await getJson("https://overpass-api.de/api/interpreter",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({data:q})}),all=o.elements||[],pt=x=>Number.isFinite(x.lon)?[x.lon,x.lat]:Number.isFinite(x.center?.lon)?[x.center.lon,x.center.lat]:null,roads=all.filter(x=>x.tags?.highway),waters=all.filter(x=>x.tags?.waterway||x.tags?.natural==="water"),near=arr=>arr.map(x=>({x,p:pt(x)})).filter(x=>x.p).map(x=>({...x,d:Math.round(hav(center,x.p))})).sort((a,b)=>a.d-b.d)[0],r=near(roads),wa=near(waters);context={roads:roads.length,waterways:waters.length,health:all.filter(x=>["hospital","clinic"].includes(x.tags?.amenity)).length,education:all.filter(x=>["school","college","university"].includes(x.tags?.amenity)).length,power:all.filter(x=>x.tags?.power).length,urbanLanduse:all.filter(x=>["residential","commercial","industrial","retail"].includes(x.tags?.landuse)).length,nearestRoad:r?{name:r.x.tags?.name||r.x.tags?.ref||"Via sem nome",distanceM:r.d,kind:r.x.tags?.highway}:undefined,nearestWater:wa?{name:wa.x.tags?.name||"Feição sem nome",distanceM:wa.d}:undefined};sources.push({name:"Entorno",provider:"OpenStreetMap / Overpass",url:"https://wiki.openstreetmap.org/wiki/Overpass_API",queriedAt:generatedAt,status:"consultado",detail:`${all.length} elementos`})}catch{sources.push({name:"Entorno",provider:"OpenStreetMap / Overpass",url:"https://wiki.openstreetmap.org/wiki/Overpass_API",queriedAt:generatedAt,status:"indisponível",detail:"Sem resposta"});limitations.push("Entorno OSM indisponível; os demais resultados permanecem válidos.")}
 limitations.push("OSM depende da completude cadastral e o DEM de 90 m não substitui levantamento de campo.");return res.status(200).json({generatedAt,location,terrain,context,market,sources,limitations});
}
