type Point=[number,number];
const rad=(v:number)=>v*Math.PI/180;
const hav=(a:Point,b:Point)=>{const R=6371008.8,dLat=rad(b[1]-a[1]),dLon=rad(b[0]-a[0]);const q=Math.sin(dLat/2)**2+Math.cos(rad(a[1]))*Math.cos(rad(b[1]))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
const normalize=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();
async function json(url:string,init?:RequestInit){const controller=new AbortController();const id=setTimeout(()=>controller.abort(),22000);try{const r=await fetch(url,{...init,signal:controller.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(id)}}
const stateCode:Record<string,string>={"minas gerais":"mg","sao paulo":"sp","goias":"go","mato grosso do sul":"ms"};
const caravelaVerified:Record<string,any>={
  "igarata|sao paulo":{period:"Emprego: jan–jun/2026 · empresas: até jul/2026",population:"11 mil",formalJobs:"2 mil",gdp:"R$ 353,2 milhões",gdpPerCapita:"R$ 33,3 mil",admissions:"555",dismissals:"348",jobBalance:"+207",newCompanies:"11"},
  "monte carmelo|minas gerais":{period:"Emprego: jan–jun/2026 · empresas: até jul/2026",population:"49,5 mil",gdp:"aprox. R$ 2 bilhões",admissions:"3.893",dismissals:"3.358",jobBalance:"+535",newCompanies:"47"}
};
function caravelaUrl(city:string,state:string){const uf=stateCode[normalize(state)];if(!uf)return "https://www.caravela.info/";const slug=city.toLowerCase().trim().replace(/\s+/g,"-");return `https://www.caravela.info/regional/${encodeURIComponent(slug).replace(/%2D/g,"-")}---${uf}`}

export async function POST(request:Request){
  try{
    const body=await request.json() as {coordinates?:Point[]};const coords=(body.coordinates||[]).filter(p=>Array.isArray(p)&&p.length>=2&&Number.isFinite(p[0])&&Number.isFinite(p[1]));
    if(coords.length<3)return Response.json({error:"A poligonal precisa ter ao menos três vértices válidos."},{status:400});
    if(coords.length>5000)return Response.json({error:"A poligonal excede 5.000 vértices. Simplifique o arquivo antes da análise."},{status:400});
    const generatedAt=new Date().toISOString(),center:[number,number]=[coords.reduce((s,p)=>s+p[0],0)/coords.length,coords.reduce((s,p)=>s+p[1],0)/coords.length];
    const lats=coords.map(p=>p[1]),lons=coords.map(p=>p[0]);const south=Math.max(-90,Math.min(...lats)-.04),north=Math.min(90,Math.max(...lats)+.04),west=Math.max(-180,Math.min(...lons)-.04),east=Math.min(180,Math.max(...lons)+.04);
    const sources:any[]=[],limitations:string[]=[];let location:any={},terrain:any=undefined,context:any=undefined,market:any=undefined;
    try{
      const rev=await json(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&addressdetails=1&zoom=10&lat=${center[1]}&lon=${center[0]}`,{headers:{"User-Agent":"EvoraIntelligence/1.1 (territorial due diligence)"}});const a=rev.address||{};location={displayName:rev.display_name,municipality:a.city||a.town||a.municipality||a.county||a.village,state:a.state};
      sources.push({name:"Geocodificação reversa",provider:"OpenStreetMap · Nominatim",url:"https://nominatim.org/",queriedAt:generatedAt,status:"consultado",detail:"Localização do centroide"});
    }catch{sources.push({name:"Geocodificação reversa",provider:"OpenStreetMap · Nominatim",url:"https://nominatim.org/",queriedAt:generatedAt,status:"indisponível",detail:"Serviço não respondeu"});limitations.push("O município não pôde ser identificado automaticamente nesta execução.")}
    if(location.municipality){try{const municipalities=await json("https://servicodados.ibge.gov.br/api/v1/localidades/municipios");const hit=municipalities.find((m:any)=>normalize(m.nome)===normalize(location.municipality)&&(!location.state||normalize(m.microrregiao?.mesorregiao?.UF?.nome||"")===normalize(location.state)));if(hit)location.ibgeCode=String(hit.id);sources.push({name:"Divisão Territorial Brasileira",provider:"IBGE · API de Localidades",url:"https://servicodados.ibge.gov.br/api/docs/localidades",queriedAt:generatedAt,status:"consultado",detail:hit?`Município identificado: ${hit.nome} (${hit.id})`:"Sem correspondência exata"})}catch{sources.push({name:"Divisão Territorial Brasileira",provider:"IBGE · API de Localidades",url:"https://servicodados.ibge.gov.br/api/docs/localidades",queriedAt:generatedAt,status:"indisponível",detail:"Serviço não respondeu"})}}
    if(location.municipality&&location.state){
      const pageUrl=caravelaUrl(location.municipality,location.state),verified=caravelaVerified[`${normalize(location.municipality)}|${normalize(location.state)}`];
      if(verified){market={provider:"Caravela",pageUrl,...verified,note:"Indicadores transcritos do perfil municipal consultado em 31/08/2026; os períodos variam por indicador."};sources.push({name:"Perfil econômico municipal",provider:"Caravela",url:pageUrl,queriedAt:generatedAt,status:"consultado",detail:verified.period})}
      else{sources.push({name:"Perfil econômico municipal",provider:"Caravela",url:pageUrl,queriedAt:generatedAt,status:"indisponível",detail:"Perfil vinculado, mas sem valores extraídos e verificados nesta execução"});limitations.push("A Caravela não possui integração pública documentada para este município; o sistema não transcreveu valores sem verificação.")}
    }
    try{
      const sample=[center,...coords.filter((_,i)=>i%Math.max(1,Math.ceil(coords.length/80))===0)].slice(0,100);const elevation=await json(`https://api.open-meteo.com/v1/elevation?latitude=${sample.map(p=>p[1]).join(",")}&longitude=${sample.map(p=>p[0]).join(",")}`);const values=(Array.isArray(elevation.elevation)?elevation.elevation:[elevation.elevation]).filter((v:any)=>Number.isFinite(v));if(values.length){const min=Math.round(Math.min(...values)),max=Math.round(Math.max(...values));terrain={min,max,mean:Math.round(values.reduce((a:number,b:number)=>a+b,0)/values.length),amplitude:max-min,samples:values.length}}sources.push({name:"Copernicus DEM GLO-90",provider:"Open-Meteo Elevation API",url:"https://open-meteo.com/en/docs/elevation-api",queriedAt:generatedAt,status:"consultado",detail:`${values.length} amostras · resolução nominal 90 m`});
    }catch{sources.push({name:"Copernicus DEM GLO-90",provider:"Open-Meteo Elevation API",url:"https://open-meteo.com/en/docs/elevation-api",queriedAt:generatedAt,status:"indisponível",detail:"Serviço não respondeu"});limitations.push("Elevação e amplitude altimétrica não foram obtidas; nenhuma estimativa substituta foi criada.")}
    try{
      const q=`[out:json][timeout:20];(way[highway](${south},${west},${north},${east});nwr[waterway](${south},${west},${north},${east});nwr[natural=water](${south},${west},${north},${east});nwr[amenity=hospital](${south},${west},${north},${east});nwr[amenity=clinic](${south},${west},${north},${east});nwr[amenity=school](${south},${west},${north},${east});nwr[amenity=college](${south},${west},${north},${east});nwr[amenity=university](${south},${west},${north},${east});nwr[power](${south},${west},${north},${east});nwr[landuse~"residential|commercial|industrial|retail"](${south},${west},${north},${east}););out center tags;`;const osm=await json("https://overpass-api.de/api/interpreter",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({data:q})});const es=osm.elements||[];const point=(e:any):Point|undefined=>Number.isFinite(e.lon)&&Number.isFinite(e.lat)?[e.lon,e.lat]:Number.isFinite(e.center?.lon)&&Number.isFinite(e.center?.lat)?[e.center.lon,e.center.lat]:undefined;const roads=es.filter((e:any)=>e.tags?.highway),waters=es.filter((e:any)=>e.tags?.waterway||e.tags?.natural==="water");const closest=(arr:any[])=>arr.map(e=>({e,p:point(e)})).filter(x=>x.p).map(x=>({...x,d:Math.round(hav(center,x.p as Point))})).sort((a,b)=>a.d-b.d)[0];const road=closest(roads),water=closest(waters);context={roads:roads.length,waterways:waters.length,health:es.filter((e:any)=>["hospital","clinic"].includes(e.tags?.amenity)).length,education:es.filter((e:any)=>["school","college","university"].includes(e.tags?.amenity)).length,power:es.filter((e:any)=>e.tags?.power).length,urbanLanduse:es.filter((e:any)=>["residential","commercial","industrial","retail"].includes(e.tags?.landuse)).length,nearestRoad:road?{name:road.e.tags?.name||road.e.tags?.ref||"Via sem nome cadastrado",distanceM:road.d,kind:road.e.tags?.highway}:undefined,nearestWater:water?{name:water.e.tags?.name||"Feição sem nome cadastrado",distanceM:water.d}:undefined};sources.push({name:"Infraestrutura e uso do solo colaborativo",provider:"OpenStreetMap · Overpass API",url:"https://wiki.openstreetmap.org/wiki/Overpass_API",queriedAt:generatedAt,status:"consultado",detail:`${es.length} elementos no recorte espacial`});
    }catch{sources.push({name:"Infraestrutura e uso do solo colaborativo",provider:"OpenStreetMap · Overpass API",url:"https://wiki.openstreetmap.org/wiki/Overpass_API",queriedAt:generatedAt,status:"indisponível",detail:"Serviço não respondeu"});limitations.push("Vias, hidrografia e equipamentos do entorno não puderam ser consultados nesta execução.")}
    limitations.push("As contagens do OpenStreetMap dependem da completude cadastral da comunidade e não substituem levantamento de campo.");limitations.push("O Copernicus DEM GLO-90 possui resolução nominal de 90 m e não substitui levantamento planialtimétrico cadastral.");limitations.push("Perímetro urbano, zoneamento, matrícula, CAR e restrições ambientais oficiais ainda exigem arquivos ou serviços municipais/estaduais específicos.");
    return Response.json({generatedAt,location,terrain,context,market,sources,limitations});
  }catch(error){return Response.json({error:error instanceof Error?error.message:"Erro inesperado na análise territorial."},{status:500})}
}
